version: '3.7'
services:
  tomee:
    build: ../images/tomee
    ports:
      - "8080:8080"
  mysql:
    build: ../images/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=adminpw
    ports:
      - "3306:3306"
  phpmyadmin:
    build: ../images/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=adminpw
    ports:
      - "8000:80"
    links:
      - mysql:db