version: '3.7'
services:
  payara:
    build: ../images/payara
    environment:
      PAYARA_ARGS: "--debug"
    ports:
      - 8080:8080
      - 4848:4848
      - 9009:9009
  db:
    build: ../images/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=adminpw
    ports:
      - "3306:3306"
  phpmyadmin:
    build: ../images/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=adminpw
    ports:
      - "8000:80"
    depends_on:
      - db